tasks:
- name: aws-cli
env:
AWS_CLI_AUTO_PROMPT: on-partial I
before:
cd /workspace
curl "https://aws cli.amazonaws.com/aws cli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
cd $THEIA_WORKSPACE_ROOT
